/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  
  //知识库
  knowledge: [
    'knowledge/introduction',
    {
      label: '1、运维',
      type: 'category', 
      link: {
        type: 'generated-index',
        keywords: ['linux','k8s'],
      },
      items: [
        {
          label: 'Linux',
          type: 'category',
          link: {            type: 'generated-index',          },
          items: [
            'knowledge/operation/linux/linux-note',
            'knowledge/operation/linux/linux-command',
            'knowledge/operation/linux/linux-vim',
          ],
        },
        {
          label: 'k8s',
          type: 'category',
          link: {            type: 'generated-index',          },
          items: [
            'knowledge/operation/k8s/k8s-note',
          ],
        },
      ]
    },
    {
      label: '2、前端',
      type: 'category', 
      link: {
        type: 'generated-index',
        keywords: ['html','javascript','node','css'],
      },
      items: [
        {
          label: 'html',
          type: 'category',
          link: {            type: 'generated-index',          },
          items: [
            'knowledge/frontEnd/html/html',
          ],
        },
        {
          label: 'JavaScript',
          type: 'doc',
          id: 'knowledge/frontEnd/javascript/javascript',
        },
        {
          label: 'NodeJs',
          type: 'category',
          link: {            type: 'generated-index',          },
          items: [
            'knowledge/frontEnd/nodejs/nodejs',
            'knowledge/frontEnd/nodejs/nodejs-nvm',
          ],
        },
      ]
    },
    {
      label: '3、后端',
      type: 'category', 
      link: {
        title: '3、后端',
        description: '语言包括Java、go、python，后续持续更新',
        type: 'generated-index',
        keywords: ['go','Java', 'python'],
      },
      items: [
        {
          label: 'Java',
          type: 'category',
          link: {            type: 'generated-index',          },
          items: [
            {
              label: '1、安装',
              type: 'category',
              link: {                type: 'generated-index',              },
              items: [
                'knowledge/backEnd/Java/安装/java-jdk',
                'knowledge/backEnd/Java/安装/java-tools-install',
              ],
            },
            {
              label: '2、基础',
              type: 'category',
              link: {                type: 'generated-index',              },
              items: [
                'knowledge/backEnd/Java/基础/java-base',
              ],
            },
            {
              label: '3、进阶',
              type: 'category',
              link: {                type: 'generated-index',              },
              items: [
                'knowledge/backEnd/Java/进阶/java-reflect',
                'knowledge/backEnd/Java/进阶/java-proxy',
              ],
            },
          ],
        },
        {
          label: 'Python',
          type: 'category',
          link: {
            type: 'generated-index',
          },
          items: [
            {
              label: '1、安装',
              type: 'category',
              link: {                type: 'generated-index',              },
              items: [
                'knowledge/backEnd/python/安装/python',
                'knowledge/backEnd/python/安装/python-pycharm',
              ],
            },
            {
              label: '2、基础',
              type: 'category',
              link: {                type: 'generated-index',              },
              items: [
                'knowledge/backEnd/python/基础/python-base',
              ],
            },
            {
              label: '3、进阶',
              type: 'category',
              link: {                type: 'generated-index',              },
              items: [
                'knowledge/backEnd/python/进阶/python-flask',
              ],
            },
          ],
        },
        {
          label: 'Go',
          type: 'category',
          link: {
            type: 'generated-index',
          },
          items: [
            {
              label: '1、安装',
              type: 'category',
              link: {                type: 'generated-index',              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'knowledge/backEnd/go/1.安装',
                },
              ],
            },
            {
              label: '2、开发',
              type: 'category',
              link: {                type: 'generated-index',              },
              items: [
                'knowledge/backEnd/go/基础/go-json-usage',
                'knowledge/backEnd/go/基础/go-send-http-request',
                'knowledge/backEnd/go/基础/go-call-js',
                'knowledge/backEnd/go/基础/go-concurrent',
                'knowledge/backEnd/go/基础/try-gin-framework',
              ],
            },
          ],
        },
      ]
    },
    {
      label: '4、数据库',
      type: 'category', 
      link: {
        type: 'generated-index',
        keywords: ['MySql','MongoDB','Redis','Elasticsearch'],
      },
      items: [
        {
          label: 'Mysql',
          type: 'category',
          link: {            type: 'generated-index',          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'knowledge/database/mysql',
            },
          ],
        },
        {
          label: 'MongoDB',
          type: 'category',
          link: {            type: 'generated-index',          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'knowledge/database/mongo',
            },
          ],
        },
        {
          label: 'Redis',
          type: 'category',
          link: {            type: 'generated-index',          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'knowledge/database/redis',
            },
          ],
        },
        {
          label: 'Elasticsearch',
          type: 'category',
          link: {            type: 'generated-index',          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'knowledge/database/elasticsearch',
            },
          ],
        },
      ],
    },
    {
      label: '5、算法',
      type: 'category',
      link: {
        type: 'doc',
        id: 'knowledge/algorithm/algorithm-introduction',
      },
      items: [
        'knowledge/algorithm/two-sum',
        'knowledge/algorithm/three-sum',
        'knowledge/algorithm/sliding-window',
        'knowledge/algorithm/double-pointer',
      ],
    },
    {
      label: '6、其它',
      type: 'category',
      link: { type: 'generated-index' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'knowledge/other',
        },
      ],
    },
  ],

  //功能介绍
  introduction: [
    'introduction/introduction',
    {
      label: '用户管理',
      type: 'category', 
      link: {
        type: 'generated-index',
        keywords: ['用户', '管理'],
      },
      items: [
        'introduction/user/userList',
        'introduction/user/authentication',
        'introduction/user/address',
      ]
    },
    {
      label: '内容管理',
      type: 'category', 
      link: {
        type: 'generated-index',
        keywords: ['内容', '管理'],
      },
      items: [
        'introduction/content/advertiseList',
      ]
    },
    {
      label: '系统管理',
      type: 'category', 
      link: {
        type: 'generated-index',
        keywords: ['系统', '管理'],
      },
      items: [
        'introduction/system/menu',
        'introduction/system/role',
      ]
    },
  ],

  //工具推荐
  tools: [
    'tools/introduction',
    'tools/everything-quick-search-local-files',
    'tools/wappalyzer-recognize-technology',
    'tools/windows-custom-right-click-menu',
    'tools/vscode-config',
    'tools/idea-config',
    'tools/vite-plugin',
    'tools/jetbrains-product-activation-method',
  ],

  //关于本站
  about: [
    'about/about',
    'about/contact',
  ],
  
};

module.exports = sidebars;
